/**
 * src/db/cola.js – Cola llamadas repository
 *
 * Covers public.cola_llamadas
 */
'use strict';

const pool = require('./pool');

/**
 * Bulk-insert candidates into cola_llamadas for a given franja.
 *
 * Equivalent to the INSERT generated by the llenar_cola_llamadas RPC
 * called in the "Crear cola de pendientes" node of the Varios flow.
 *
 * @param {Array<{candidatoId: string, prioridad: number, franjaProgramada: string, horaProgramada: string}>} entries
 * @param {string} fechaProgramada – YYYY-MM-DD
 * @returns {Promise<number>} – number of rows inserted
 */
async function bulkInsertQueue(entries, fechaProgramada) {
  if (entries.length === 0) return 0;

  const values = [];
  const placeholders = entries.map((e, i) => {
    const base = i * 5;
    values.push(
      e.candidatoId,
      e.prioridad,
      e.franjaProgramada,
      e.horaProgramada || null,
      fechaProgramada,
    );
    return `($${base + 1}, $${base + 2}, $${base + 3}, $${base + 4}, $${base + 5}, 'PENDIENTE')`;
  });

  const sql = `
    INSERT INTO public.cola_llamadas
      (candidato_id, prioridad, franja_programada, hora_programada, fecha_programada, estado)
    VALUES ${placeholders.join(', ')}
    ON CONFLICT DO NOTHING
  `;

  const result = await pool.query(sql, values);
  return result.rowCount;
}

/**
 * Get pending queue items for today, ordered by priority desc then created_at asc.
 * Limits to `limit` rows.
 *
 * Equivalent to "Traer siguiente cola" node in Varios.
 *
 * @param {string} fechaHoy   – YYYY-MM-DD
 * @param {number} limit
 * @returns {Promise<Array>}
 */
async function getPendingQueueItems(fechaHoy, limit) {
  const { rows } = await pool.query(
    `SELECT *
     FROM public.cola_llamadas
     WHERE estado = 'PENDIENTE'
       AND fecha_programada = $1
     ORDER BY prioridad DESC, created_at ASC
     LIMIT $2`,
    [fechaHoy, limit],
  );
  return rows;
}

/**
 * Mark a queue item as EN_CURSO.
 *
 * Equivalent to "Marcar EN_CURSO en cola" node in Varios.
 *
 * @param {number} colaId
 * @returns {Promise<void>}
 */
async function markQueueItemEnCurso(colaId) {
  await pool.query(
    `UPDATE public.cola_llamadas SET estado = 'EN_CURSO' WHERE id = $1`,
    [colaId],
  );
}

/**
 * Update queue items for a candidate on a given date to a final estado.
 *
 * @param {string} candidatoId
 * @param {string} fechaHoy     – YYYY-MM-DD
 * @param {string} nuevoEstado  – 'COMPLETADA' | 'CANCELADA'
 * @returns {Promise<void>}
 */
async function finalizeCandidateQueueItems(candidatoId, fechaHoy, nuevoEstado) {
  await pool.query(
    `UPDATE public.cola_llamadas
     SET estado = $1
     WHERE candidato_id = $2
       AND fecha_programada = $3
       AND estado IN ('PENDIENTE', 'EN_CURSO')`,
    [nuevoEstado, candidatoId, fechaHoy],
  );
}

module.exports = {
  bulkInsertQueue,
  getPendingQueueItems,
  markQueueItemEnCurso,
  finalizeCandidateQueueItems,
};

